### ISSUE TITLE
Multi Args

### ISSUE THREAD

**Issue by Steellgold** [Androz2091/multilingual-discord-bot#6]
Hello, in `language("TEXT",argument1, argument2)` cela ne fonctionne pas, dans le message qui devrait envoyer au lieu de mettre a un endroit l'argument1 sa met les 2 au même endroit et celui qui s'affiche pas ce met en "undefined" 

peut m'aider ?

![image](https://user-images.githubusercontent.com/51505384/88058494-d5f49c00-cb63-11ea-8711-19fee04059bd.png)
![image](https://user-images.githubusercontent.com/51505384/88058535-e278f480-cb63-11ea-846f-b01876116c86.png)

**Comment by Androz2091** [comment]
Bonjour,
cela devrait être réglé

**Comment by Steellgold** [comment]
Merci je vais tester ca

**Comment by Steellgold** [comment]
sa fonctionne merci ;) 

(et gg pour la rapidité 🤣)
